import { Hono } from 'hono'
import { CustomerDatastore } from './datastore/customers'
import { CustomerService } from './services/customer-service'
import { CustomerHandler } from './handlers/customer-handler'

// Define context variables type
type Variables = {
  customerHandler: CustomerHandler
}

// Env type is auto-generated by Wrangler in worker-configuration.d.ts
const app = new Hono<{ Bindings: Env; Variables: Variables }>()

// Basic route
app.get('/', (c) => {
  return c.text('Hello! Try these D1 endpoints: /customers, /customer/:id, /create-customer')
})

// Initialize dependencies and wire up routes
app.use('*', async (c, next) => {
  // Create datastore → service → handler chain
  const datastore = new CustomerDatastore(c.env.my_d1_database)
  const service = new CustomerService(datastore)
  const handler = new CustomerHandler(service)

  // Attach handler to context for route handlers to use
  c.set('customerHandler', handler)
  await next()
})

// Customer routes
app.get('/customers', (c) => {
  return c.get('customerHandler').listCustomers(c)
})

app.get('/customer/:id', (c) => {
  return c.get('customerHandler').getCustomer(c)
})

app.post('/create-customer', (c) => {
  return c.get('customerHandler').createCustomer(c)
})

app.get('/stats', (c) => {
  return c.get('customerHandler').getStats(c)
})

export default app
