import { Hono } from "hono";
import type { AppContext } from "./fetch";
import * as customerHandler from "./handlers/customer-handler";

// Env type is auto-generated by Wrangler in worker-configuration.d.ts
const app = new Hono<AppContext>();

// Basic route
app.get("/", (c) => {
  return c.text("Hello! Try these D1 endpoints: /customers, /customer/:id, /create-customer");
});

// Customer routes - clean and simple!
app.get("/customers", (c) => {
  return customerHandler.listCustomers(c, c.env.packlib_d1);
});

app.get("/customer/:id", (c) => {
  return customerHandler.getCustomer(c, c.env.packlib_d1);
});

app.post("/create-customer", (c) => {
  return customerHandler.createCustomer(c, c.env.packlib_d1);
});

app.get("/stats", (c) => {
  return customerHandler.getStats(c, c.env.packlib_d1);
});

export default app;
